---
title: "Final Project - Predicting PDAC with Circulating miRNA - Decision Tree Only"
authors: "Madison Blake, Kristyn Gumpper-Fedus, Sean Kirkpatrick"
date: "`r Sys.Date()`"
output: html_document
---

# Predicting PDAC with Circulating miRNA - Decision Tree Only

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

dir.create("Data", showWarnings = FALSE, recursive = TRUE)

source("R/model_only_report_helpers.R")
source("R/run_fold_dt.R")
source("R/run_limma_paired.R")
source("R/differential_expression_filter_fn.R")
```

```{r constants, include=FALSE}
set.seed(31415)

normalized_data_file <- "Data/GSE314577/GSE314577_VUMC_miRNA_normalized_data.xlsx"
metadata_file <- "Data/GSE314577/GSE314577_VUMC_Metadata_ch_revised.xlsx"
limma_rds_file <- "Data/Full train_filter_results.rds"

log2_pseudocount <- 1
run_limma_analysis <- FALSE
train_fraction <- 0.8
k <- 10

fold_filter_top_n <- 25
dt_importance_plot_top_n <- max(20L, fold_filter_top_n)
dt_cp <- 0.001
dt_maxdepth <- 30

demographic_covariates <- c("Sex", "Race", "Age")
factor_demographic_covariates <- c("Sex", "Race")
use_model_covariates <- TRUE
model_covariates <- if (use_model_covariates) demographic_covariates else character(0)

limma_group_term <- "CC"
limma_adjustment_covariates <- demographic_covariates
filter_stat_cols <- c(
  "miRNA",
  "mean_control",
  "mean_case",
  "mean_diff",
  "limma_log_fc",
  "limma_avg_expr",
  "limma_t",
  "limma_p_value",
  "limma_adj_p_value",
  "limma_b"
)
```

```{r shared_inputs, include=FALSE}
analysis_inputs <- load_model_only_pipeline_data(
  normalized_data_file = normalized_data_file,
  metadata_file = metadata_file,
  log2_pseudocount = log2_pseudocount,
  train_fraction = train_fraction,
  run_limma_analysis = run_limma_analysis,
  limma_rds_file = limma_rds_file,
  filter_stat_cols = filter_stat_cols,
  fold_filter_top_n = fold_filter_top_n,
  limma_group_term = limma_group_term,
  limma_adjustment_covariates = limma_adjustment_covariates
)

train_set <- analysis_inputs$train_set
holdout <- analysis_inputs$holdout
train_filter_results <- analysis_inputs$train_filter_results
miRNA_all_columns <- analysis_inputs$miRNA_all_columns
```

```{r model_feature_pool, include=FALSE}
selected_miRNA <- miRNA_all_columns
```

```{r model_run, include=FALSE}
model_runner <- function(fold_inputs) {
  dt_runner <- get("run_fold_dt", mode = "function")

  dt_runner(
    fold_inputs,
    cp_dt = dt_cp,
    maxdepth = dt_maxdepth
  )
}

cv_results <- run_single_model_cv(
  train_set = train_set,
  k = k,
  selected_miRNA = selected_miRNA,
  model_name = "decision_tree",
  model_runner = model_runner,
  model_covariates = model_covariates,
  factor_model_covariates = factor_demographic_covariates
)

holdout_results <- run_single_model_holdout(
  train_set = train_set,
  holdout = holdout,
  selected_miRNA = selected_miRNA,
  model_name = "decision_tree",
  model_runner = model_runner,
  model_covariates = model_covariates,
  factor_model_covariates = factor_demographic_covariates
)
```

```{r final_objects, include=FALSE}
decision_tree_results <- list(
  train_filter_results = train_filter_results,
  preselected_miRNA = selected_miRNA,
  selected_miRNA = holdout_results$final_model_output$selected_miRNA,
  cv_predictions = cv_results$cv_predictions,
  cv_tuning = cv_results$cv_tuning,
  cv_feature_counts = cv_results$cv_feature_counts,
  cv_preselected_feature_counts = cv_results$cv_preselected_feature_counts,
  cv_selected_variables = cv_results$cv_selected_variables,
  cv_selected_miRNA = cv_results$cv_selected_miRNA,
  cv_feature_importance = cv_results$cv_feature_importance,
  cv_summary = cv_results$cv_summary,
  holdout_roc = holdout_results$holdout_roc,
  holdout_predictions = holdout_results$holdout_predictions,
  holdout_summary = holdout_results$holdout_summary,
  final_fold_inputs = holdout_results$final_fold_inputs,
  final_model_output = holdout_results$final_model_output,
  feature_importance = holdout_results$final_model_output$feature_importance
)
```

## Final Decision Tree Feature Importance

```{r dt_feature_importance_table, echo=FALSE, results='asis'}
dt_feature_importance_table <- holdout_results$final_model_output$feature_importance
dt_feature_importance_table <- dt_feature_importance_table[
  dt_feature_importance_table$variable_type == "miRNA",
  ,
  drop = FALSE
]
dt_feature_importance_table <- utils::head(dt_feature_importance_table, dt_importance_plot_top_n)

if (!nrow(dt_feature_importance_table)) {
  cat("<p>The final decision tree did not return any miRNA used in primary splits or any miRNA with nonzero importance.</p>\n")
} else {
  cat(
    paste0(
      "<p>For the decision tree, miRNA were considered selected only if they appeared in one or more primary splits of the final tree. ",
      "The table below ranks miRNA by total loss reduction and distinguishes split-used miRNA from miRNA with nonzero importance only.</p>\n"
    )
  )

  knitr::kable(
    transform(
      dt_feature_importance_table[
        ,
        c(
          "importance_rank",
          "variable",
          "importance_value",
          "primary_split_count",
          "selected_for_final"
        )
      ],
      selected_for_final = ifelse(selected_for_final, "Yes", "No")
    ),
    format = "html",
    row.names = FALSE,
    digits = 3,
    caption = "Decision-tree miRNA feature-importance ranking on the final holdout model"
  )
}
```

```{r dt_feature_importance_plot, echo=FALSE, fig.width=8, fig.height=7}
plot_feature_importance_ranking(
  holdout_results$final_model_output$feature_importance,
  model_label = "Decision Tree",
  top_n = dt_importance_plot_top_n,
  variable_type = "miRNA",
  selected_label = "Used in tree",
  unselected_label = "Importance only"
)
```

## Holdout ROC Curve

```{r holdout_roc_plot, echo=FALSE, fig.width=6, fig.height=6}
plot_model_roc_curve(
  holdout_results$holdout_predictions,
  model_label = "Decision Tree",
  dataset_label = "Holdout"
)
```

```{r}
```